from fastapi import FastAPI, WebSocket
import numpy

app = FastAPI()

#IMPORTANT DENIAL
all_denials = [
    "I'm afraid I can't do that.",
    "Sorry, that's not possible.",
    "I'll have to pass this time.",
    "Unfortunately, I have to say no.",
    "I'm unable to help with that.",
    "That won't work for me.",
    "I'm not available for this.",
    "I need to decline.",
    "Not this time, sorry.",
    "I appreciate you asking, but I can't.",
    "I'm honoured you asked, but no.",
    "Unfortunately, I can't commit to that.",
    "I have other priorities at the moment.",
    "I can't take that on right now.",
    "Sadly, that's a no from me.",
    "I'm going to have to decline the offer.",
    "I won't be able to participate.",
    "Thank you, but I'm not interested.",
    "Not right now, maybe another time.",
    "I'm flattered, but I must decline.",
    "I'm tied up with something else.",
    "I'm already booked.",
    "I don't have the capacity for that.",
    "I'm committed elsewhere.",
    "I'll have to say no for now.",
    "I'm not in a position to do that.",
    "I can't take that responsibility.",
    "Sorry, that's outside my scope.",
    "It's not something I can take on.",
    "I have to focus on other things.",
    "I'm unable to accommodate that request.",
    "That's not feasible for me.",
    "I can't agree to that.",
    "Sadly, I'm unavailable.",
    "I've got too much going on.",
    "I need to decline politely.",
    "I'll have to opt out.",
    "That's not something I can help with.",
    "I'm choosing not to.",
    "I'm not the right person for this.",
    "I'm going to sit this one out.",
    "No thank you.",
    "I don't feel comfortable saying yes.",
    "I'd rather not.",
    "I can't assist with that.",
    "I won't be moving forward with that.",
    "That doesn't work with my schedule.",
    "Regretfully, no.",
    "I need to decline due to time constraints.",
    "Not something I can support.",
    "I have to say no — sorry.",
    "I don't have the bandwidth for this.",
    "It's not doable on my end.",
    "I wish I could, but I can't.",
    "I'm declining for personal reasons.",
    "That's off the table for me.",
    "I'm choosing to prioritise other projects.",
    "I'll pass on this opportunity.",
    "I can't factor that in right now.",
    "I can't make that commitment.",
    "I'm going to say no.",
    "That's not a direction I want to take.",
    "I've decided not to accept.",
    "I can't swing that right now.",
    "I can't get involved in that.",
    "I'm stepping away from that request.",
    "I have to refuse.",
    "That's not something I can offer.",
    "I don't have the resources for that.",
    "I'm unable to oblige.",
    "It's a no from me, but thank you.",
    "I can't meet that request at this time.",
    "Sadly, that won't be happening.",
    "I'm maxed out currently.",
    "That's not aligned with my plans.",
    "I'm unable to assist.",
    "I'm not interested in pursuing that.",
    "I respectfully decline.",
    "I can't participate right now.",
    "I've got enough commitments already.",
    "That doesn't fit my priorities.",
    "I'm unable to take that path.",
    "That's outside what I can do.",
    "I'm tapped out at the moment.",
    "I'm going to decline the request.",
    "I'm not able to say yes to that.",
    "No, that won't be possible.",
    "I need to decline the invitation.",
    "I simply can't do that.",
    "I'm not able to provide that.",
    "I'm not able to follow through.",
    "I'm unable to agree.",
    "I'm afraid that won't happen.",
    "I'm going to decline, thanks.",
    "I'm going to focus elsewhere.",
    "I can't fit that in.",
    "I'll have to refuse this time.",
    "I've decided against it.",
    "I'm unable to comply.",
    "Hard pass — but I appreciate the thought!"
]

@app.websocket("/ws")
async def websocker_endpoint(websocket: WebSocket):
    await websocket.accept()
    while True:
        data = await websocket.receive_text()
        random_text_output_index = numpy.random.randint(0, len(all_denials))
        await websocket.send_text(all_denials[random_text_output_index])